### ISSUE TITLE
Aiohappybase not working in openshift

### ISSUE THREAD

**Issue by ofekzaza** [python-happybase/aiohappybase#1]
Hello

I have a project which use happybase to communicate with hbase. And i have tried to change the code to use aiohappybase.
The code worked perfectly in my pc (windows os).
However, when i uploaded the code to openshift it didbt worked and crashed on the first line - from aiohappybase import Connection.

##The error
```
From aiohappybase import Connection

Aiohappybase/--init-- line 13 : 
From .connection import host port Connection

Aiohappybase/connection line 12
From thriftpy2.contrib.aio.transport import (

Thriftpy2/contrib/aio/trasport/--init-- line 13
From .base import TAsyncTransportException

Thriftpy2/contrib/aio/transport/base line 7
From thriftpy2.transport import TBuffedTransportFactory

Thriftpy2/transport/buffered/--init-- line 68
From .cybuffered import TCyBufferedTransport, TCyBufferedTransportFactory #noqa

ModuleNotFoundError: No module named thriftpy2.transport.buffered.cybuffered
```

The error does not happens in windows. But it does happens in openshift.

Thanks for helping

**Comment by wbolster** [comment]
while this triggered by importing `aiohappybase`, the stack trace shows that the error does not originate from this library, but from [thriftpy2](https://github.com/Thriftpy/thriftpy2), so please take it to their bug tracker.

**Comment by aiudirog** [comment]
Just so the information is here: thriftpy2 is trying to use compiled extensions on Linux, which weren't built. Just reinstall thriftpy2 directly with pip and it should build them.
