### ISSUE TITLE
how to get best performance by scan

### ISSUE THREAD

**Issue by nekow33** [python-happybase/aiohappybase#6]
when I try to read from table by `table.scan` to read about 1,000,000 lines data. it takes a lot of time

![image](https://user-images.githubusercontent.com/33059912/120128201-1006e380-c1f4-11eb-8780-762973504d76.png)

I had google it already, but didn't get answer. so I have to ask here

Is there any way to make scan faster? or other way to get data from HBase fastest？

**Comment by aiudirog** [comment]
My use case for HBase revolves around fewer large rows instead of many small rows so I haven't done much in the way of testing multi-row scan performance. Let me put together some performance tests and look over your use case and see what metrics I can find.

Also, could you share some information about your system? I'm wondering if there is a significant performance different on Linux vs. Windows where the sync API can take advantage of the Cython compiled extensions ThriftPy2 provides.

**Comment by nekow33** [comment]
@aiudirog my system info is 
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
```
and cpu is `Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz` with `64GB RAM`

client and server is the same machine

actually I think query is fast but data transport is very slow. 
I tried to store the same data about `100MB` with another structure like
![image](https://user-images.githubusercontent.com/33059912/120252750-f9c25b80-c2b7-11eb-9ef7-7109a8f3ddfc.png)
it also takes a long time 

I guess that maybe my hbase or thirft config is not effective， here is my `hbase-site.xml`
```
<property>
  <name>hbase.cluster.distributed</name>
  <value>false</value>
</property>
<property>
  <name>hbase.tmp.dir</name>
  <value>/opt/hbase/other/tmpdir</value>
</property>
<property>
  <name>hbase.unsafe.stream.capability.enforce</name>
  <value>false</value>
</property>
<property>
  <name>hbase.rootdir</name>
  <value>file:///opt/hbase/data</value>
</property>
<property>
  <name>hbase.zookeeper.property.dataDir</name>
  <value>/opt/hbase/other/zookeeperdata</value>
</property>
<property>
  <name>hbase.table.sanity.checks</name>
  <value>false</value>
</property>
<property>
  <name>hbase.regionserver.thrift.compact</name>
  <value>true</value>
</property>
<property>
  <name>hbase.regionserver.thrift.framed</name>
  <value>true</value>
</property>
<property>
   <name>hbase.thrift.server.socket.read.timeout</name>
   <value>86400000</value>
</property>
<property>
   <name>hbase.thrift.connection.max-idletime</name>
   <value>86400000</value>
</property>
```
and config in `hbase-env.sh`
```
export HBASE_HEAPSIZE=12G
export HBASE_OFFHEAPSIZE=10G
export HBASE_MANAGES_ZK=true
```

**Comment by aiudirog** [comment]
From my tests, I'm seeing similar performance to you with a large number of individual cells. It looks like the deserialzataion per cell that is killing it.

Out of curiosity, why are you trying to use HBase for this data? HBase is meant for large, loosely structured data where each column family on each row can be used to store a dictionary of assorted data with potentially large values per key. It looks like you have structured, timestamped records which something like [Hive](https://hive.apache.org/) or [QuestDB](https://questdb.io/) would handle much better.

**Comment by nekow33** [comment]
I use HBase because I often add columns for my data structure. I think a Column-oriented DBMS is the most suitable. I will try to use different databases to find the best database.

thanks for your advice.

**Comment by aiudirog** [comment]
Unfortunately having the flexibility to change the schema on the fly is a tradeoff with performance. Improving performance is definitely still a worthwhile task, but it would have to be done on the underlying ThriftPy2 library where all the magic happens.
